---

- hosts: web_servers
  become: true
  tasks:

  - name: install nginx
    tags: nginx,ubuntu
    package:
      name: 
        - "{{ nginx_package }}"
      state: latest
      update_cache: yes

