---

- hosts: web_servers 
  become: true
  tasks:

  - name: uninstall nginx
    tags: nginx,ubuntu
    package:
      name: 
        - "{{ nginx_package }}"
      state: absent
      update_cache: yes

