---

- hosts: web_servers
  become: true
  tasks:

  - name: uninstall apache and php package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes

