- name: install mariadb package (Fedora) 
  tags: fedora,db,mariadb
  dnf:
        name: mariadb
        state: latest
  when: ansible_distribution == "Fedora"

- name: install mariadb package (Ubutu) 
  tags: ubuntu,db,mariadb
  apt:
        name: mariadb-server
        state: latest
  when: ansible_distribution == "Ubuntu"
